Coverage: add tests for `core_ext/time`
This adds missing test coverage for `core_ext/time`. This also surfaced
a code issue with the second condition. Ruby `DateTime` does not
implement the `#utc` method so calling `datetime.to_datetime.utc`
actually raises an error. I removed this in favor of calling `.to_time`
on anything that responds to it.

```irb
> Date.today.to_datetime.utc
(irb):6:in `<main>': undefined method `utc' for #<DateTime: 2023-10-22T00:00:00+00:00 ((2460240j,0s,0n),+0s,2299161j)> (NoMethodError)
```